#!/usr/bin/env python3
# Checks that subclass terms inherit all typed relations from their parent terms.
#
# When a term B declares `subClassOf` pointing at term A, every instance of B
# is also an instance of A. Typed relations on A (such as produces, consumes,
# conveys, exposes) therefore apply to B by inheritance and should be
# explicitly declared on B as well.
#
# Relations checked for inheritance:
#   produces  — output flow or exchange generated by a function or activity
#   consumes  — input flow or exchange used by a function or activity
#   conveys   — flow or exchange that circulates through an interface
#   exposes   — flow or exchange exposed by a functional element
#   fires     — transition fired by an active state
#
# For each child term that declares subClassOf, the script looks up each
# parent term and reports any relation that the parent declares but the
# child does not. Missing relations are reported but the script does NOT
# modify any file — use it as a read-only audit step in the CI pipeline.
#
# Exit codes:
#   0 — always (gaps are reported as warnings, not errors)
#
# Run this script after inject_uris.py and before generate_glossary.py.

import json
import sys
from pathlib import Path

BASE_IRI = "https://www.3se.info/3se-onto/terms/"
TERMS_DIR = Path("terms")

# Relations that must be inherited from parent to child when subClassOf is used.
INHERITED_FIELDS: list[str] = [
    "produces",
    "consumes",
    "conveys",
    "exposes",
    "fires",
]


def load_index(terms_dir: Path) -> dict[str, dict]:
    """Return a mapping of URI -> term data for all JSON files in terms_dir."""
    index: dict[str, dict] = {}
    if not terms_dir.exists():
        return index
    for fp in sorted(terms_dir.glob("*.json")):
        try:
            data = json.loads(fp.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue  # let validate_glossary.py report parse errors
        uri = data.get("@id") or (BASE_IRI + fp.stem)
        index[uri] = data
    return index


def build_ancestor_index(index: dict[str, dict]) -> dict[str, set[str]]:
    """
    Return a mapping of URI -> set of all ancestor URIs via transitive closure
    of subClassOf. Only URIs present in the index are tracked; external URIs
    (e.g. BFO) appear in ancestor sets but have no entry of their own.
    """
    direct: dict[str, list[str]] = {}
    for uri, data in index.items():
        parents = data.get("subClassOf") or []
        if isinstance(parents, str):
            parents = [parents]
        direct[uri] = list(parents)

    ancestors: dict[str, set[str]] = {uri: set() for uri in index}
    changed = True
    while changed:
        changed = False
        for uri in index:
            for parent in direct.get(uri, []):
                if parent not in ancestors[uri]:
                    ancestors[uri].add(parent)
                    changed = True
                for grandparent in ancestors.get(parent, set()):
                    if grandparent not in ancestors[uri]:
                        ancestors[uri].add(grandparent)
                        changed = True
    return ancestors


def stem_from_uri(uri: str) -> str:
    """Return the filename stem from a full term URI."""
    if uri.startswith(BASE_IRI):
        return uri[len(BASE_IRI):]
    return uri


def main() -> int:
    index = load_index(TERMS_DIR)
    if not index:
        print("⚠️  No terms found — nothing to check.")
        return 0

    ancestor_index = build_ancestor_index(index)
    gaps: list[tuple[str, str, dict[str, list]]] = []

    for uri, data in sorted(index.items()):
        parents = data.get("subClassOf", [])
        if not parents:
            continue

        child_title = data.get("title", stem_from_uri(uri))

        for parent_uri in parents:
            parent = index.get(parent_uri)
            if not parent:
                continue  # external URI (e.g. BFO) — skip

            parent_title = parent.get("title", stem_from_uri(parent_uri))
            missing: dict[str, list] = {}

            for field in INHERITED_FIELDS:
                parent_val = parent.get(field) or []
                if isinstance(parent_val, str):
                    parent_val = [parent_val]
                child_val = data.get(field) or []
                if isinstance(child_val, str):
                    child_val = [child_val]
                child_set = set(child_val)
                missing_vals = [
                    v for v in parent_val
                    if v not in child_set
                    and not any(v in ancestor_index.get(c, set()) for c in child_val)
                ]
                if missing_vals:
                    missing[field] = missing_vals

            if missing:
                gaps.append((child_title, parent_title, missing))

    if not gaps:
        print("✓ No inheritance gaps found.")
        return 0

    print(f"⚠️  {len(gaps)} inheritance gap(s) found:\n")
    for child_title, parent_title, missing in gaps:
        print(f"  child : {child_title}")
        print(f"  parent: {parent_title}")
        for field, values in missing.items():
            targets = ", ".join(stem_from_uri(v) for v in values)
            print(f"    missing {field}: [{targets}]")
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
